<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="UserPC" failures="1" tests="5" name="Command line test" time="0.154" errors="0" timestamp="2021-12-30T15:35:59 MSK">
  <testcase classname="CalcTest1" name="dataProviderTest" time="0.006"/>
  <testcase classname="CalcTest1" name="dataProviderTest" time="0.0"/>
  <testcase classname="CalcTest1" name="dataProviderTest" time="0.0"/>
  <testcase classname="CalcTest1" name="testSum" time="0.001"/>
  <testcase classname="CalcTest1" name="testSum1" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [6] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [6] but found [5]
at CalcTest1.testSum1(CalcTest1.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- testSum1 -->
</testsuite> <!-- Command line test -->
